### ISSUE TITLE
Close up shop?

### ISSUE THREAD

**Issue by jradavenport** [jradavenport/ThirdWay#4]
It seems like this code has moved or morphed conceptually in to [friedrich](https://github.com/bmorris3/friedrich)

So grand ideas started here, but should we close this up if its not going to be developed under this branding any longer?

**Comment by bmorris3** [comment]
I don't think this repo needs to close for certain, there's still more than
my way to skin this cat. But if you'd like to housekeep, that's ok!

On Tuesday, February 2, 2016, James Davenport notifications@github.com
wrote:

> It seems like this code has moved or morphed conceptually in to friedrich
> https://github.com/bmorris3/friedrich
> 
> So grand ideas started here, but should we close this up if its not going
> to be developed under this branding any longer?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jradavenport/ThirdWay/issues/4.

## 

Brett Morris
Graduate Student
Astronomy and Astrobiology
University of Washington
http://brettmorr.is

**Comment by jradavenport** [comment]
:+1: I'll leave it then, maybe we can revisit at some point
